baseURL = 'https://trimclient.com/'
languageCode = 'en-au'
title = 'Trimclient'
theme = 'up-business-theme'
enableRobotsTXT = true
summaryLength = 10

[services]
  [services.googleAnalytics]
    ID = 'G-KP2SCYD47P'

[params]
title = "Trimclient"
description = "Secure managed computing for high-accountability environments"

location = [
    "P.O.Box 5178, Hughesdale, Vic 3166, Australia",
    "Cyber IT Solutions Pty Ltd, Suite 49, Erasmus Business Park, 45 Riversdale Road, Hawthorn, Victoria 3122, Australia"
]
copyright = "© 2026 Cyber IT Solutions Pty Ltd"

[params.favicons]
themeColor = "#026670"
backgroundColor = "#f5f0eb"
faviconColor = "#026670"

[params.social]

[[params.contact]]
content = "info@cyber.com.au"
url = "mailto:info@cyber.com.au"
[[params.contact]]
content = "+613 7019 4225"
url = "tel:+61370194225"

[menus]

[[menus.main]]
name = "Security"
url = "/security"
weight = 1

[[menus.main]]
name = "Deployment planning"
url = "/deployment-planning"
weight = 2

[[menus.main]]
name = "Why consolidated"
url = "/why-consolidated"
weight = 3

[[menus.main]]
name = "Who we serve"
url = "/who-we-serve"
weight = 4

[[menus.buttons]]
name = "Enquiries"
url = "/#enquiries"
weight = 5
pre = "btn btn-primary"

[[menus.footer]]
name = "Home"
url = "/"
weight = 1

[[menus.footer]]
name = "Security"
url = "/security"
weight = 2

[[menus.footer]]
name = "Deployment planning"
url = "/deployment-planning"
weight = 3

[[menus.footer]]
name = "Why consolidated"
url = "/why-consolidated"
weight = 4

[[menus.footer]]
name = "Who we serve"
url = "/who-we-serve"
weight = 5

[[menus.footer]]
name = "Enquiries"
url = "/#enquiries"
weight = 6

[taxonomies]
# No taxonomies

[module.hugoVersion]
extended = true
min = '0.131.0'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
